# Generated by Django 2.2.11 on 2020-03-09 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_widgetinstance_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetinstance',
            name='column',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(11, 'column must be between 0 and 11')]),
        ),
        migrations.AlterField(
            model_name='widgetinstance',
            name='width',
            field=models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1, 'width must be between 1 and 12'), django.core.validators.MaxValueValidator(12, 'width must be between 1 and 12')]),
        ),
    ]
