---

stages:
  - django-checks
  - imports
  - style
  - documentation
  - test

image: python:2

services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: internewshid
  MYSQL_ROOT_PASSWORD: passw0rd
  DJANGO_SECRET_KEY: 'nde2wr2r)#a*%n$!(zl8#3v_o!sp=hd9vbv%*e6atgr0dp=b(7'

before_script:
  - virtualenv --python=python2.7 .ve
  - source .ve/bin/activate

checks:
  stage: django-checks
  script:
    - python manage.py check
    - python manage.py makemigrations --check

isort:
  stage: imports
  script:
    - |
      isort internewshid \
      --recursive \
      --check-only \
      --diff \
      --settings-path=setup.cfg

pylama:
  stage: style
  script:
    - pylava internewshid

pytest:
  stage: test
  script:
    - pytest -v
