---

image: aptivate/pyenv-pythons:latest

services:
  - mysql:5.7

variables:
  MYSQL_ROOT_PASSWORD: internewshid
  MYSQL_DATABASE: internewshid
  APTIVATE_CLI_MYSQL_USER: root
  APTIVATE_CLI_MYSQL_PASS: "$MYSQL_ROOT_PASSWORD"
  APTIVATE_CLI_MYSQL_HOST: mysql
  FIXTURES: "internewshid/hid/fixtures/bangladesh-refugee-crisis.json"

before_script:
  - apt update && apt install -y nodejs node-less
  - pip install pipenv aptivate-cli
  - apc deploy --no-input
  - pipenv run python manage.py loaddata $FIXTURES

gitlab-ci:
  script:
    - apc checks
    - apc pylava
    - apc isort
    - apc pytest -v --cov
