# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_layer', '0006_message_network_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='translation',
            field=models.TextField(blank=True),
        ),
    ]
