# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_layer', '0009_message_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='age',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='ennumerator',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='gender',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
