# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_layer', '0010_auto_20181204_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='feedback_type',
            field=models.CharField(blank=True, choices=[(b'CONCERN', b'Concern'), (b'QUESTION', b'Question'), (b'RUMOUR', b'Rumour')], default=None, max_length=100),
        ),
    ]
