# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_layer', '0012_auto_20181205_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='ennumerator',
            new_name='enumerator',
        ),
    ]
