# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-13 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_layer', '0013_auto_20181213_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='feedback_type',
        ),
    ]
