# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-23 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_layer', '0015_customconstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='internal_id',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
