# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-23 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_layer', '0016_message_internal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='internal_id',
            new_name='external_id',
        ),
    ]
