# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-16 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_layer', '0019_message_sub_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='collection_type',
            field=models.CharField(blank=True, max_length=190),
        ),
    ]
