# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-16 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_layer', '0021_auto_20191216_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='source',
        ),
    ]
