# Generated by Django 2.2.11 on 2020-03-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_layer', '0023_auto_20200309_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='enumerator',
            new_name='contributor',
        ),
    ]
