# Generated by Django 2.2.11 on 2020-03-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_layer', '0024_auto_20200319_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='language',
            field=models.CharField(blank=True, max_length=190),
        ),
    ]
