# Generated by Django 2.2.11 on 2020-03-26 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_layer', '0026_message_risk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Key', max_length=190, unique=True, verbose_name='Key')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Value', max_length=190, verbose_name='Value')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_layer.Key', verbose_name='Key')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='data_layer.Message', verbose_name='Message')),
            ],
        ),
    ]
