# Generated by Django 2.2.11 on 2020-03-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0004_taxonomy_vocabulary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='multiplicity',
            field=models.CharField(choices=[('optional', 'Zero or One'), ('multiple', 'Zero or More')], default='optional', max_length=30),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='vocabulary',
            field=models.CharField(choices=[('fixed', 'Not modifiable by any user, system only'), ('closed', 'Only admin users who have permission to define and edit taxonomies'), ('open', 'Any user who has permission to use taxonomies')], default='closed', max_length=30),
        ),
    ]
