# Generated by Django 2.2.10 on 2020-03-05 15:11

from django.db import migrations


def delete_unwanted_importers(apps, schema_editor):
    Profile = apps.get_model('chn_spreadsheet', 'SheetProfile')
    Profile.objects.filter(label='etc').delete()
    Profile.objects.filter(label='kobo_master').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chn_spreadsheet', '0014_auto_20191216_1054'),
    ]

    operations = [
        migrations.RunPython(delete_unwanted_importers)
    ]
