# Generated by Django 2.2.11 on 2020-03-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chn_spreadsheet', '0015_auto_20200309_1832'),
        ('chn_spreadsheet', '0015_delete_etc_and_kobo_master_importers'),
    ]

    operations = [
    ]
